### ISSUE TITLE
Could not find a matching version of package tonysm/dbcreatecommand

### ISSUE THREAD

**Issue by guilherme90** [tonysm/laravel-paratest#2]
Hi,

When trying to install this package using the `composer require tonysm/dbcreatecommand` command, I get the error...

>  [InvalidArgumentException]
  Could not find a matching version of package tonysm/dbcreatecmd. Check the package spelling, your version constrain
  t and that the package is available in a stability which matches your minimum-stability (dev).

How install it?
Thanks.

**Comment by pvledoux** [comment]
It looks like it is locked to Laravel 5.8. Any chance to upgrade it?

**Comment by tonysm** [comment]
I was mainly toying around with this idea but decided to upgrade to L8 and really publish on packagist (previous you had to add the GitHub URL to your composer.json repositories list so you could pull it).

You should be able to pull it with composer now with:

```bash
composer require tonysm/laravel-paratest --dev
```
